name: Leather Luscious - Luxury In Its Rawwwr - Handmade
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14399
title: Leather Luscious - Luxury In Its Rawwwr - Handmade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6efe9'
    - '#010101'
    - '#fec416'
    - '#947864'
    - '#f42538'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
