name: Leather Luscious - Luxury In The Rawwwr
favicon: null
layout_spectrum: 0.2491
typography_spectrum: 0.1115
title: Leather Luscious - Luxury In Its Rawwwr - Handmade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b50101'
    - '#626262'
    - '#c8c8c8'
  brandStrength: 0
  lightness: 0.7777561279945076
  saturation: 0.25
  rhythmicContrast: 0.4759864374063909
purpose: []
